### ISSUE TITLE
Endless loop for failed streams

### ISSUE THREAD

**Issue by OreniOS** [awsdocs/aws-ios-developer-guide#12]
When stream is not configured correctly, trying to submit the records results in endless submission loop.

Console log boils down to:

**{"__type":"AccessDeniedException","Message":"User: arn:aws:sts::XXXX:assumed-role/XXXX/CognitoIdentityCredentials is not authorized to perform: firehose:PutRecordBatch on resource: arn:aws:firehose:eu-west-1:XXXX:deliverystream/Events-Delivery-Stream"}**

**Comment by ebattalio** [comment]
Hi, the docs have been migrated to https://github.com/awsdocs/aws-mobile-developer-guide/. 

If this problem persists, please open a new issue in that repository. Thanks!
