### ISSUE TITLE
Update mobile analytics guide

### ISSUE THREAD

**Issue by simonbromberg** [awsdocs/aws-ios-developer-guide#6]
Looks like the mobile analytics [guide](https://github.com/awsdocs/aws-ios-developer-guide/blob/master/doc_source/analytics.rst) was only partially updated to reflect recent changes (still mentions the identity pool ID) 

Excerpt (problems bolded):
...

> **Initialize an :command:**`AWSMobileAnalytics` client. In doing so, you'll need to provide the appId value that you generated in the Amazon Mobile Analytics console. The appId is used to group your data in the Amazon Mobile Analytics console.

```
AWSMobileAnalyticsConfiguration *analyticsConfiguration = [[AWSMobileAnalyticsConfiguration alloc] init];
[analyticsConfiguration setServiceConfiguration:serviceConfiguration];
AWSMobileAnalytics *analytics = [AWSMobileAnalytics mobileAnalyticsForAppId:@"yourAppId" configuration: analyticsConfiguration];
```

> where "yourAppId" is the appId value from the Amazon Mobile Analytics console **and "cognitoId" is the Cognito identity pool ID.**

Trying to figure out how to update client initialization to use this configuration object but neither this nor the [documentation site](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/getting-started-analytics.html) explain it properly. What is `serviceConfiguration` and how do you switch from the old method to this new one?

**Comment by dzucker-amzn** [comment]
Thanks Simon! I fixed this oversight.

**Comment by simonbromberg** [comment]
So what's "serviceConfiguration" and how do you set it up? It's not defined in the example.

**Comment by ebattalio** [comment]
The documentation has been migrated to https://github.com/awsdocs/aws-mobile-developer-guide/. Please reopen an issue in that repository for additional feedback. Thanks!
